### ISSUE TITLE
Installing pip requirements fails and data related questions

### ISSUE THREAD

**Issue by kelhaji** [xcfcode/DDAMS#10]
Hi!

I am trying to use the code on a new dataset to get summaries. 

# Installation issues
When setting up the requirements I ran into a few issues with regard to installing the pip requirements. Here are steps I have taken:

`git clone https://github.com/xcfcode/DDAMS.git`
`cd DDAMS`
`conda create -n ddams python=3.7`
`pip install -r requirements.txt`

After running the last command, I get the following error:
<img width="1097" alt="Screen Shot 2022-01-05 at 14 41 16" src="https://user-images.githubusercontent.com/33722723/148227345-89517980-fb59-4ff1-8a0e-e44cf14e5908.png">

For ease, this is the text of the error:
`Collecting torch-cluster==1.4.4
  Downloading torch_cluster-1.4.4.tar.gz (18 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/anaconda3/envs/ddams/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/s4/94wbh2bd7_x1zpthktk_k5q00000gn/T/pip-install-wetzfkx_/torch-cluster_48529a159cc6448fbcd0d4cf88e577bd/setup.py'"'"'; __file__='"'"'/private/var/folders/s4/94wbh2bd7_x1zpthktk_k5q00000gn/T/pip-install-wetzfkx_/torch-cluster_48529a159cc6448fbcd0d4cf88e577bd/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/s4/94wbh2bd7_x1zpthktk_k5q00000gn/T/pip-pip-egg-info-dzkcak7c
         cwd: /private/var/folders/s4/94wbh2bd7_x1zpthktk_k5q00000gn/T/pip-install-wetzfkx_/torch-cluster_48529a159cc6448fbcd0d4cf88e577bd/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/s4/94wbh2bd7_x1zpthktk_k5q00000gn/T/pip-install-wetzfkx_/torch-cluster_48529a159cc6448fbcd0d4cf88e577bd/setup.py", line 2, in <module>
        import torch
    ModuleNotFoundError: No module named 'torch'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bd/5f/01c5799cd1f81f9956f03a0e1d9a861e020a598dd411d9bd3c3c1dd5b8a4/torch_cluster-1.4.4.tar.gz#sha256=7907f3f270116cb299bdd4f88de497a85b3b34cf127910ffe0a6131e16620123 (from https://pypi.org/simple/torch-cluster/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement torch-cluster==1.4.4 (from versions: 0.1.1, 0.2.3, 0.2.4, 1.0.1, 1.0.3, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3a1, 1.4.3, 1.4.4, 1.4.5, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9)
ERROR: No matching distribution found for torch-cluster==1.4.4`

I get the error on both macOS Sierra 10.12.6 and Ubuntu 20.04. I have tried to change the dependencies in `requirements.txt` so they no longer conflict, but this always results in some kind of error later on: 

- on macOS Sierra 10.12.6 I get `AssertionError: Torch not compiled with CUDA enabled` when running `translate.py` after manually changing the dependencies to match. 

- on Ubuntu 20.04 I get `ImportError: /home/khalid/anaconda3/envs/ddams2/lib/python3.7/site-packages/torch_scatter/scatter_cpu.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZNK2at11ATenOpTable11reportErrorEN3c1012TensorTypeIdE` when running `translate.py` after manually changing the dependencies to match. 

# Data pre-processing

I intend to use your code to get a summary of a meeting based on a meeting transcript. In order to do so, if I understand everything correctly, you need a `test.src`, `test.tgt`, `test.seg`, `test.speaker`, and `test.relation` file. In issue #5 you had already given a script to generate those files based on the AMI dataset. However, if you only have a single meeting transcript how do you generate those files? In particular, the `test.tgt` file seems to be a summary in itself already, do you need to have such a file already beforehand?

Thank you for your help.

**Comment by xcfcode** [comment]
update: working on this issue~

**Comment by xcfcode** [comment]
For the second problem **Data pre-processing**:
1. If you just want to generate a meeting summary without calculating ROUGE scores, you **do not** need a `test.tgt` file, since this file is used for final evaluation.
2. If you want to process your own meetings, you have to refer to [DialogueDiscourseParser](https://github.com/xcfcode/DDAMS/tree/main/DialogueDiscourseParser), first, you can prepare your transcripts as [data format](https://github.com/xcfcode/DDAMS/tree/main/DialogueDiscourseParser#data-format), then, get the discourse relations, afterward, you can use the script described in issue #5 to generate above files.
